<script src="./modules/scriptaculous/js/prototype.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/scriptaculous.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/builder.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/controls.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/dragdrop.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/EditInPlace.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/effects.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/slider.js" type="text/javascript"></script>
<script src="./modules/scriptaculous/js/sound.js" type="text/javascript"></script>